# 设置 Gradle 命令使用的默认内存。可由用户或命令行参数覆盖。
# 这是为 Minecraft 反编译流程提供足够内存所必需的。
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## 环境属性

# Minecraft 版本必须与 Forge 版本一致，才能获得有效的构件
minecraft_version=1.20.1
# Minecraft 版本范围可使用任意正式版 Minecraft 作为边界。
# 快照版、预发布版和候选发布版由于不遵循标准版本规范，
# 不能保证正确排序。
minecraft_version_range=[1.20.1,1.21)
# Forge 版本必须与 Minecraft 版本一致，才能获得有效的构件
forge_version=47.4.10
# Forge 版本范围可使用任意 Forge 版本作为边界，或与加载器版本范围匹配
forge_version_range=[47,)
# 加载器版本范围只能使用 Forge/FML 的主版本号作为边界
loader_version_range=[47,)
# 用于映射的映射通道。
# 默认支持的映射通道有 ["official", "snapshot", "snapshot_nodoc", "stable", "stable_nodoc"]。
# 额外的映射通道可通过 Gradle 插件中的 "channelProviders" 扩展进行注册。
#
# | 通道      | 版本                 |                                                                                |
# |-----------|----------------------|--------------------------------------------------------------------------------|
# | official  | MCVersion            | 来自 Mojang 映射文件的官方字段/方法名                                           |
# | parchment | YYYY.MM.DD-MCVersion | 在官方映射之上叠加的社区开源参数名与 Javadoc                                     |
#
# 使用 'official' 或 'parchment' 映射时，必须注意 Mojang 许可协议。
# 更多信息见：https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md
#
# Parchment 是由 ParchmentMC 维护的非官方项目，与 Minecraft Forge 分离。
# 使用其映射需要额外配置，见 https://parchmentmc.org/docs/getting-started
mapping_channel=official
# 从映射通道中查询的映射版本。
# 该值必须符合对应映射通道要求的格式。
mapping_version=v2023.09.03


## 模组属性

# 模组唯一标识符。必须为英文小写，并符合正则 [a-z][a-z0-9_]{1,63}
# 必须与主模组类中 @Mod 注解所用的 String 常量一致。
mod_id=frost_delight
# 模组的人类可读显示名称。
mod_name=Frost Delight
# 模组许可证。可在 https://choosealicense.com/ 查看选项。默认值为 All Rights Reserved。
mod_license=All Rights Reserved
# 模组版本。参见 https://semver.org/
mod_version=1.0.0-1.20.1
# 模组的 group ID。仅在发布为 Maven 仓库构件时重要。
# 应与模组源码使用的基础包名一致。
# 参见 https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.starry3430.frost_delight
# 模组作者。用于在模组列表中展示的简单文本字符串。
mod_authors=Starry-3430
# 模组描述。用于在模组列表中展示的简单多行文本字符串。
mod_description=🧊Beat the heat with Frosty Delights! 🧊Craft popsicles and ice cream bowls, place them anywhere, and enjoy! Features plenty of unique flavors, thirst system compatibility with ThirstWasTaken, melting mechanics, and special effects like Fire Resistance. Includes the Ice Cream Maker and Popsicle Molds to expand your culinary empire!
